### ISSUE TITLE
Upgrade to OpenTelemetry 0.19.0

### ISSUE THREAD

**Issue by hillna** [j2gg0s/otsql#4]
I am currently using OpenTelemetry 0.19.0 and attempting to use this wrapper for database instrumentation.

However, I am having issues installing it due to breaking changes in OpenTelemetry, specifically:
```
github.com/j2gg0s/otsql imports
        go.opentelemetry.io/otel/label: module go.opentelemetry.io/otel@latest found (v0.19.0), but does not contain package go.opentelemetry.io/otel/label
```

I understand that OpenTelemetry is in alpha and these changes are more or less expected.

Can this be upgraded to support OpenTelemetry 0.19.0?

Thanks!

**Comment by k1ng440** [comment]
please check this pull request #5

**Comment by j2gg0s** [comment]
Thanks your pr
