### ISSUE TITLE
Not using returned context from Before in After for non Context aware methods

### ISSUE THREAD

**Issue by jrdnull** [j2gg0s/otsql#8]
For example:
https://github.com/j2gg0s/otsql/blob/6c531765c2d98104b034b7081686e75c512ca3cf/conn.go#L535-L544

Could be changed to:
```go
func (t otTx) Commit() (err error) {
	evt := newEvent(t.Options, t.connID, MethodCommit, "", nil)
	ctx := before(t.Hooks, context.TODO(), evt)
	defer func() {
		evt.Err = err
		after(t.Hooks, ctx, evt)
	}()

	return t.Tx.Commit()
}
```

### Use case

To be able to add a span for Commit/Rollback to my trace, I am storing my trace context in my hook on a call to BeginContext, then looking it up using Event.Conn as a key so I can add a span for Commit/Rollback even though no context is passed to it.

---

I'll make this change on a fork and open a PR if you're interested in this (as well as for all the other context unaware methods to use the result of before in the after callback)

**Comment by j2gg0s** [comment]
Thanks for your work.

For `ExecContext` and `Exec`, most of the implements of `Driver` will auto prioritize `ExecContext`. So we may not need to do more work for these methods.

However, `Commit` and `Rollback` has no context version, this is the problem.
If we want to trace `Commit` and `Rollback`:
- First, we should use `ctx` return by `after` in `before`.
- Second, we should return **current ctx** in before.

The **current** means we should save ``ctx`` before call of `Commit`/`Rollback`, this is difficult and complicated.
